spring:
  application:
    name: TDD Workshop Sample Application
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialize: true
    initialization-mode: always
  sql:
    init:
      encoding: UTF-8
      schema-locations: "classpath:schema.sql"
      data-locations: "classpath:data.sql"
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
hibernate:
  globally_quoted_identifiers: true

