package com.example.tdd_workshop.schedule.db;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
class ScheduleRepositoryTest {

    @Autowired
    private ScheduleRepository scheduleRepository;

    @Test
    void shouldSaveAndFindSchedule() {
        // Arrange
        ScheduleRecord schedule = new ScheduleRecord(
                null, // ID will be generated by the database
                "Test Schedule",
                "This is a test schedule.",
                LocalDateTime.of(2023, 10, 1, 10, 0),
                LocalDateTime.of(2023, 10, 1, 12, 0)
        );

        // Act
        var savedSchedule = scheduleRepository.save(schedule);

        // Assert
        assertThat(savedSchedule).isNotNull();
    }
}
